### ISSUE TITLE
Jamming on photo background

### ISSUE THREAD

**Issue by mml1** [jbeck018/React-Jamming#3]
Just like you added a transparent black bg to the search results, add a transparent black background to your whole page. Currently, it is a bit hard to read the title Jammming. You could also try changing the font color of Jamming.

**Comment by jbeck018** [comment]
Yeah, I thought that as well. There are some other css updates that I wanted to make after the fact, but decided I would change them later. I plan on implementing a few other things into the project before I add it to my portfolio and thought it would be a good time to do it then.
